name: Cypress Tests

on: workflow_dispatch

jobs:
  Cypress-Setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: echo "BROWSER_PATH=$(which chrome)" >> $GITHUB_ENV

      - name: Run e2e tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

        with:
          spec: cypress/e2e/
          browser: chrome
          config: |
            video=false

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**
          retention-days: 30
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos/**
          retention-days: 30
          if-no-files-found: ignore
